# --- Stage 1: Build stage ---
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app

# Poore folder content ko direct copy karo bina naam ke jhanjhat ke
COPY . .

# Subfolder ke andar ja kar maven build run karo
RUN cd spotifyclone && mvn clean package -DskipTests

# --- Stage 2: Runtime stage ---
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/spotifyclone/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
