# --- Stage 1: Build stage ---
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app

# Sabse pehle poore folder ko copy karo
COPY . .

# Yeh command automatic subfolder ke andar ja kar pom.xml dhoondh legi (chahe naam kuch bhi ho)
RUN cd $(find . -maxdepth 2 -name "pom.xml" -exec dirname {} \;) && mvn clean package -DskipTests

# --- Stage 2: Runtime stage ---
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

# Yeh automatic bne hue jar file ko runtime mein copy kar lega
COPY --from=build /app/**/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
