spring.application.name=spotifyclone
spring.datasource.url=jdbc:mysql://localhost:3306/spotify_clone
spring.datasource.username=root
spring.datasource.password=nitesh

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
logging.level.org.springframework.web=DEBUG
